### PR TITLE
it will build as a framework for carthage

### PR DESCRIPTION
**Pull request by RunsCode**
it will build as a framework for carthage ...

### CODE REVIEW

**Review by RunsCode — COMMENTED** [review]
ok

**Comment by RunsCode** [comment]
000

**Review by wy358688217 — COMMENTED** [review]
ok1

**Review by zhuhejiaodeyuanfen — COMMENTED** [review]
ok3

**Review by zhuhejiaodeyuanfen — COMMENTED** [review]
merge

**Comment by zhuhejiaodeyuanfen** [comment]
11122

**Review by zhuhejiaodeyuanfen — COMMENTED** [review]
646546

**Pull request merged**
